/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_GW_Volunteers_Volunteer_HoursTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_GW_Volunteers_Volunteer_Ha0STrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new GW_Volunteers__Volunteer_Hours__c());
    }
}